# Generated by Django 2.0.5 on 2018-06-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='categories',
            new_name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_categories',
            field=models.ManyToManyField(to='restaurant.FoodCategory'),
        ),
    ]
